name: Nix CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Enable Nix flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Add IntersectMBO cache
        uses: cachix/cachix-action@v15
        with:
          name: intersectmbo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Linux x86_64
        run: nix build . --accept-flake-config

      - name: Build Linux aarch64
        run: nix build .#packages.aarch64-linux.default --accept-flake-config

      - name: Build Darwin x86_64
        run: nix build .#packages.x86_64-darwin.default --accept-flake-config

      - name: Build Darwin aarch64
        run: nix build .#packages.aarch64-darwin.default --accept-flake-config

      - name: Build Windows (cross-compilation via hydraJobs)
        run: nix build '.#hydraJobs.x86_64-linux.x86_64-w64-mingw32.packages.cardano-addresses:exe:cardano-address' --accept-flake-config

      - name: Build Docker image
        run: nix build .#packages.x86_64-linux.docker-image --accept-flake-config

  cache:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Enable Nix flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Push to IntersectMBO cache
        uses: cachix/cachix-action@v15
        with:
          name: intersectmbo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          pushFilter: |
            !**/*-test**
            !**/*-tests**
