name: Continuous Integration (Windows)

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: 'GitHub actions env workaround'
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append'

    - name: ðŸ“¥ Checkout repository
      uses: actions/checkout@v1

    - name: ðŸ§° Setup Stack
      run: |
        PowerShell.exe -Command "&{Invoke-WebRequest -OutFile ${installdir}\\stack.zip https://get.haskellstack.org/stable/windows-x86_64.zip ; 7z e ${installdir}\\stack.zip -o${installdir} stack.exe ; Remove-Item ${installdir}\\stack.zip}"

    - name: ðŸ’¾ Cache Dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ hashFiles('stack.yaml') }}

    - name: ðŸ“¸ Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        # Update keyring to allow packages signed by recent contributors:
        #
        #   error: mingw-w64-x86_64-mpc: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
        curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-1~20220623-1-any.pkg.tar.zst
        curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-1~20220623-1-any.pkg.tar.zst.siz
        stack --no-terminal exec -- pacman -U --noconfirm msys2-keyring-1~20220623-1-any.pkg.tar.zst
        stack --no-terminal exec -- pacman -Syu --no-confirm
        stack --no-terminal exec -- pacman -S --noconfirm mingw-w64-x86_64-pcre
        stack --no-terminal exec -- pacman -S --noconfirm mingw-w64-x86_64-pkg-config
        stack --no-terminal test --bench --only-snapshot

    - name: ðŸ”¨ Build & Test
      run: |
        stack --no-terminal test --bench --haddock --no-haddock-deps --no-run-benchmarks --flag cardano-addresses:release
        stack --no-terminal path --local-bin
        stack --no-terminal install --haddock --no-haddock-deps --flag cardano-addresses:release

    - name: ðŸ·ï¸ Variables
      id: variables
      shell: bash
      run: |
        echo "stack_local_bin=$(stack path --local-bin)" >> $GITHUB_OUTPUT

    - name: ðŸ“Ž Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-exe
        path: ${{ steps.variables.outputs.stack_local_bin }}
