name: Continuous Integration (Windows)

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: 'GitHub actions env workaround'
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append'

    - name: ğŸ“¥ Checkout repository
      uses: actions/checkout@v1

    - name: ğŸ§° Setup Stack
      uses: mstksg/setup-stack@69e4283faeb7a89f26326daa36e9cc0fa7a023bd

    - name: ğŸ’¾ Cache Dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ hashFiles('stack.yaml') }}

    - name: ğŸ“¸ Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-1~20211228-1-any.pkg.tar.zst
        curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-1~20211228-1-any.pkg.tar.zst.sig
        stack --no-terminal exec -- pacman -U --noconfirm msys2-keyring-1~20211228-1-any.pkg.tar.zst
        stack --no-terminal exec -- pacman -Syu --no-confirm
        stack --no-terminal exec -- pacman -S --noconfirm mingw-w64-x86_64-pcre
        stack --no-terminal exec -- pacman -S --noconfirm mingw-w64-x86_64-pkg-config
        stack --no-terminal test --bench --only-snapshot

    - name: ğŸ”¨ Build & Test
      run: |
        stack --no-terminal test --bench --haddock --no-haddock-deps --no-run-benchmarks --flag cardano-addresses:release
        stack --no-terminal path --local-bin
        stack --no-terminal install --haddock --no-haddock-deps --flag cardano-addresses:release

    - name: ğŸ·ï¸ Variables
      id: variables
      shell: bash
      run: |
        echo ::set-output name=stack_local_bin::$(stack path --local-bin)

    - name: ğŸ“ Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-exe
        path: ${{ steps.variables.outputs.stack_local_bin }}
